feat invite events
harmony-org/harmony pull request #41
Opened 2020-12-01 14:20 UTC by CyberKnight007

- Added the following gateway events to the library
- [x] inviteCreate
- [x] inviteDelete

- Added a invite manager extended from the base manager in the managers folder to manage the invite events
- Modified structures/guild.ts to add the invite manager property

2020-12-01 15:00 UTC, DjDeveloperr commented
Looks good to me - just needs few changes as in the review.

2020-12-01 15:12 UTC, DjDeveloperr requested changes

2020-12-01 15:17 UTC, DjDeveloperr requested changes

2020-12-01 15:17 UTC, DjDeveloperr commented on src/gateway/handlers/inviteDelete.ts
> +  if (cachedInvite === undefined) return
Also, can we emit an `inviteDeleteUncached` event here? It's followed in other events -- would be good to see it here aswell, for compatibility purposes.

2020-12-02 02:32 UTC, DjDeveloperr requested changes

2020-12-02 02:32 UTC, DjDeveloperr commented on src/gateway/handlers/inviteCreate.ts
> +    // had to use `as ChannelPayload` because the _get method returned `ChannelPayload | undefined` which errored
Please fix the lint error here, use `as unknown) as ChannelPayload)` please.

2020-12-02 02:32 UTC, DjDeveloperr commented on src/gateway/handlers/inviteCreate.ts
> +import getChannelByType from '../../utils/getChannelByType.ts'
Lint error, remove unused imports!

2020-12-02 02:32 UTC, DjDeveloperr commented on src/gateway/handlers/inviteDelete.ts
> +    return gateway.client.emit('inviteDeleteUncached', cachedInvite)
Won't it be better to emit with some more details? Such as a PartialInvite interface containing channel, guild, and invite code perhaps?

2020-12-02 02:32 UTC, DjDeveloperr commented on src/managers/invites.ts
>        this.client.rest
Any plan on completing this method? 🤔

2020-12-02 08:04 UTC, Helloyunho requested changes

2020-12-02 08:04 UTC, Helloyunho commented on src/gateway/handlers/inviteCreate.ts
> +  // Weird case, shouldn't happen
nope it can happen if the user created a group invite using a self bot

2020-12-02 08:04 UTC, Helloyunho commented on src/gateway/handlers/inviteDelete.ts
> +  // Weird case, shouldn't happen
this too

2020-12-02 08:16 UTC, Helloyunho commented on src/gateway/handlers/inviteCreate.ts
> +  // Weird case, shouldn't happen
I didn't see the message in Discord. Resolved

2020-12-02 09:56 UTC, Helloyunho approved these changes

2020-12-02 09:57 UTC, merged