feat(structures): add Emoji methods
harmony-org/harmony pull request #74
Opened 2020-12-25 16:33 UTC by ayntee

- Added Emoji#edit()
- Added Emoji#delete()

2020-12-26 02:42 UTC, DjDeveloperr requested changes

2020-12-26 02:42 UTC, DjDeveloperr commented on src/structures/emoji.ts
> +  roles: string[] | null
What do you think about allowing user to put `Role | Role[]` for `roles` too? And making all props optional here will make sense.

2020-12-26 07:14 UTC, DjDeveloperr approved these changes
LGTM

2020-12-27 00:27 UTC, AkiaCode approved these changes

2020-12-27 23:50 UTC, Helloyunho approved these changes
I think it's good

2020-12-29 03:46 UTC, merged