feat: add Role#tags prop
harmony-org/harmony pull request #77
Opened 2020-12-26 06:12 UTC by ayntee

- Added Role#tags property

2020-12-27 23:59 UTC, Helloyunho requested changes

2020-12-27 23:59 UTC, Helloyunho commented on src/types/role.ts
> +  tags: RoleTagsPayload | null
[From the discord docs](https://discord.com/developers/docs/topics/permissions#role-object) it should be undefined instead of null

2020-12-28 08:17 UTC, AkiaCode approved these changes

2020-12-28 14:36 UTC, Helloyunho approved these changes
lgtm

2020-12-29 06:12 UTC, DjDeveloperr approved these changes
LGTM

2020-12-29 06:12 UTC, merged