Guild awaitAvailiable method and removing redundant code in guild structure
harmony-org/harmony pull request #82
Opened 2021-01-01 15:59 UTC by ZiomaleQ

2021-01-05 03:01 UTC, Helloyunho approved these changes
lgtm

2021-01-05 09:38 UTC, DjDeveloperr commented
There's a new event now: guildLoaded which fires when a guild is loaded, user can await the event using Promise and conditional checks.

2021-01-05 14:42 UTC, DjDeveloperr commented
Just a small UX improvement, what about resolving to loaded `Guild` from the method?

2021-01-06 10:01 UTC, DjDeveloperr requested changes

2021-01-06 10:01 UTC, DjDeveloperr commented on src/structures/guild.ts
> +      if(!this.unavailable) return;
Instead of returning, resolve to `this`.

2021-01-06 10:01 UTC, DjDeveloperr commented on src/structures/guild.ts
> +      this.client.on('guildLoaded', listener);
If the event never occurs, this listener always stays... memory leaks can be there. So, add a timeout to reject and make it configurable through a param in the method.

2021-01-07 10:14 UTC, DjDeveloperr approved these changes
LGTM - thanks! 🚀

2021-01-07 10:14 UTC, merged